# my-laravel-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-laravel-app
  labels:
    app: my-laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-laravel-app
  template:
    metadata:
      labels:
        app: my-laravel-app
    spec:
      containers:
      - name: my-laravel-app
        image: boyke09/img-web-laravel
        ports:
        - containerPort: 8000
        env:
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: db_laravel
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: root

---

apiVersion: v1
kind: Service
metadata:
  name: my-laravel-app
  labels:
    app: my-laravel-app
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: my-laravel-app     
