apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql  # Sesuai untuk testing lokal atau dev environment. Gantilah jika diperlukan untuk produksi.

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Tidak perlu selector jika hanya ada satu PV yang cocok atau biarkan Kubernetes memilih PV yang tersedia.
  volumeMode: Filesystem

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: db_laravel
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql  # Direktori standar MySQL untuk data
          name: mysql-pvc  # Nama volume yang konsisten
      volumes:
      - name: mysql-pvc  # Pastikan nama volume konsisten
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
